pub struct ApiGroupCall {
    chat_id: Option<String>,
    is_loaded: Option<bool>,
    id: String,
    access_hash: String,
    join_muted: Option<bool>,
    can_change_join_muted: Option<bool>,
    can_start_video: Option<bool>,
    join_date_asc: Option<bool>,
    schedule_start_subscribed: Option<bool>,
    participants_count: i32,
    params: Option<serde_json::Value>,
    title: Option<String>,
    stream_dc_id: Option<i32>,
    record_start_date: Option<i64>,
    schedule_date: Option<i64>,
    version: i32,
    invite_hash: Option<String>,
    next_offset: Option<String>,
    is_speaker_disabled: Option<bool>,
}

pub struct PhoneCallAction {
    is_outgoing: bool,
    is_video: Option<bool>,
    duration: Option<i32>,
    reason: Option<String>,
}

pub struct ApiPhoneCall {
    state: Option<String>,
    is_connected: Option<bool>,
    id: String,
    access_hash: Option<String>,
    admin_id: Option<String>,
    participant_id: Option<String>,
    is_video: Option<bool>,
    date: Option<i64>,
    start_date: Option<i64>,
    receive_date: Option<i64>,
    p2p_allowed: Option<bool>,
    need_rating: Option<bool>,
    need_debug: Option<bool>,
    reason: Option<String>,
    duration: Option<i32>,
    emojis: Option<String>,
    g_a: Option<Vec<i32>>,
    g_b: Option<Vec<i32>>,
    p_last: Option<Vec<i32>>,
    random_last: Option<Vec<i32>>,
    g_a_or_b: Option<Vec<i32>>,
    g_a_hash: Option<Vec<i32>>,
    key_fingerprint: Option<String>,
    is_muted: Option<bool>,
    is_battery_low: Option<bool>,
}
